# [START cloud_sql_proxy_k8s_sa]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartlock-microservice
spec:
  selector:
    matchLabels:
      app: smartlock-service
  replicas: 1 #CHANGE
  minReadySeconds: 45
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smartlock-service
    spec:
      serviceAccountName: ksa-cluster
      # [END cloud_sql_proxy_k8s_sa]
      # [START cloud_sql_proxy_k8s_secrets]
      containers:
      - name: smartlock-service
        # ... other container configuration
        image: havyx/smartlock-service:v3
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 9001
            protocol: TCP
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: padotec-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: padotec-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: padotec-secret
              key: database
      # [END cloud_sql_proxy_k8s_secrets]
      # [START cloud_sql_proxy_k8s_container]
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          - "-ip_address_types=PRIVATE"

          # Replace DB_PORT with the port the proxy should listen on
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=euphoric-axiom-311918:southamerica-east1:padotec-postgres=tcp:5432"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        # Resource configuration depends on an application's requirements. You
        # should adjust the following values based on what your application
        # needs. For details, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
#        resources:
#          requests:
            # The proxy's memory use scales linearly with the number of active
            # connections. Fewer open connections will use less memory. Adjust
            # this value based on your application's requirements.
#            memory: "2Gi"
            # The proxy's CPU use scales linearly with the amount of IO between
            # the database and the application. Adjust this value based on your
            # application's requirements.
#            cpu:    "1"
      # [END cloud_sql_proxy_k8s_container]
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: smartlock-service
  name: smartlock-service
  namespace: default
spec:
  ports:
    - # nodePort: 30701 #CHANGE
      port: 9001 #CHANGE
      protocol: TCP
      targetPort: 9001 #CHANGE
  selector:
    app: smartlock-service
  sessionAffinity: None #CHANGE
  type: LoadBalancer